### ISSUE TITLE
week 3 homework

### ISSUE THREAD

**Issue by ObadaElSharbatly** [HackYourFuture/React#656]
Hello
In week3 hackyourtemp project we require to use the second route as `/:cityId` but the only allowed package for free is this 
https://openweathermap.org/api/one-call-api

and we only can fetch by using latitude and longitude
so I suggest just to say make another route or make it more clear to be easier for students because it's already hard week 😅
best regards

**Comment by robvk** [comment]
Good point, will adjust it for next class. Thanks for the heads up!

**Comment by robvk** [comment]
The project has been changed so this does not apply anymore.
