### ISSUE TITLE
In week1 reading material

### ISSUE THREAD

**Issue by FikretYilmaz** [HackYourFuture/React#657]
Hi, The link of useMemo in week 1 doesn't work it could be changed with this: https://www.youtube.com/watch?v=THL1OPn72vo

**Comment by robvk** [comment]
![image](https://user-images.githubusercontent.com/23367061/146004863-944a6258-c06d-4828-8038-a58a5e95b638.png)

Seems to work for me, it is linking to that one.

**Comment by FikretYilmaz** [comment]
Interesting! It didn't work yesterday but now it's working. Thank you very much.
